-- ==========================================
-- LifeOS Pro — Supabase PostgreSQL Database Schema
-- ==========================================
-- Copia y pega este script en el "SQL Editor" de tu panel de Supabase 
-- para inicializar todas las tablas requeridas por la aplicación 
-- con políticas de seguridad y Row Level Security (RLS).

-- Habilitar extensión para UUIDs si no está habilitada
create extension if not exists "uuid-ossp";

-- 1. TABLA: SETTINGS (Configuraciones de Usuario)
create table if not exists public.settings (
    user_id text primary key, -- Puede mapear al uuid auth.uid() en formato string
    pin_hash text,
    pin_enabled boolean default false,
    theme text default 'dark',
    active_modules text[] default array['documents', 'vehicles', 'expenses', 'subscriptions', 'warranties', 'packages', 'homes', 'tasks']::text[],
    notifications_enabled boolean default true,
    plan text default 'free',
    billing_cycle text,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS en settings
alter table public.settings enable row level security;

-- Políticas de RLS para settings
drop policy if exists "Los usuarios pueden leer su propia configuración" on public.settings;
create policy "Los usuarios pueden leer su propia configuración"
    on public.settings for select
    using (auth.uid()::text = user_id or user_id = 'local_user');

drop policy if exists "Los usuarios pueden insertar su propia configuración" on public.settings;
create policy "Los usuarios pueden insertar su propia configuración"
    on public.settings for insert
    with check (auth.uid()::text = user_id or user_id = 'local_user');

drop policy if exists "Los usuarios pueden actualizar su propia configuración" on public.settings;
create policy "Los usuarios pueden actualizar su propia configuración"
    on public.settings for update
    using (auth.uid()::text = user_id or user_id = 'local_user');


-- 2. TABLA: DOCUMENTS (Documentos encriptados)
create table if not exists public.documents (
    id bigint generated by default as identity primary key,
    user_id text not null,
    name text not null,
    category text not null,
    document_number text, -- Texto encriptado en el cliente
    issue_date text,
    expiry_date text,
    issuer text,
    notes text, -- Texto encriptado en el cliente
    tags text[] default array[]::text[],
    attachment text, -- Base64 o URL del archivo
    file_name text,
    is_sensitive boolean default false,
    archived boolean default false,
    deleted boolean default false,
    favorite boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.documents enable row level security;

drop policy if exists "Acceso completo a documentos propios" on public.documents;
create policy "Acceso completo a documentos propios"
    on public.documents for all
    using (auth.uid()::text = user_id or user_id = 'local_user')
    with check (auth.uid()::text = user_id or user_id = 'local_user');

create index if not exists idx_documents_user_expiry on public.documents(user_id, expiry_date);


-- 3. TABLA: VEHICLES (Vehículos)
create table if not exists public.vehicles (
    id bigint generated by default as identity primary key,
    user_id text not null,
    brand text not null,
    model text not null,
    year integer not null,
    plates text not null,
    color text,
    mileage integer default 0,
    fuel_type text,
    next_service_mileage integer,
    insurance_expiry text,
    verification_expiry text,
    circulation_card text,
    notes text,
    image text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.vehicles enable row level security;

drop policy if exists "Acceso completo a vehículos propios" on public.vehicles;
create policy "Acceso completo a vehículos propios"
    on public.vehicles for all
    using (auth.uid()::text = user_id or user_id = 'local_user')
    with check (auth.uid()::text = user_id or user_id = 'local_user');


-- 4. TABLA: VEHICLE SERVICES (Bitácora de Servicios)
create table if not exists public.vehicle_services (
    id bigint generated by default as identity primary key,
    vehicle_id bigint references public.vehicles(id) on delete cascade not null,
    type text not null,
    cost numeric(12,2) not null,
    date text not null,
    mileage integer not null,
    details text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.vehicle_services enable row level security;

drop policy if exists "Acceso completo a servicios de vehículos propios" on public.vehicle_services;
create policy "Acceso completo a servicios de vehículos propios"
    on public.vehicle_services for all
    using (
        exists (
            select 1 from public.vehicles 
            where public.vehicles.id = vehicle_id 
            and (public.vehicles.user_id = auth.uid()::text or public.vehicles.user_id = 'local_user')
        )
    );


-- 5. TABLA: EXPENSES (Egresos y Presupuesto)
create table if not exists public.expenses (
    id bigint generated by default as identity primary key,
    user_id text not null,
    amount numeric(12,2) not null,
    date text not null,
    category text not null,
    payment_method text not null,
    merchant text not null,
    description text,
    tags text[] default array[]::text[],
    is_recurring boolean default false,
    related_module text,
    related_id bigint,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.expenses enable row level security;

drop policy if exists "Acceso completo a gastos propios" on public.expenses;
create policy "Acceso completo a gastos propios"
    on public.expenses for all
    using (auth.uid()::text = user_id or user_id = 'local_user')
    with check (auth.uid()::text = user_id or user_id = 'local_user');

create index if not exists idx_expenses_user_date on public.expenses(user_id, date);


-- 6. TABLA: SUBSCRIPTIONS (Suscripciones)
create table if not exists public.subscriptions (
    id bigint generated by default as identity primary key,
    user_id text not null,
    name text not null,
    plan text not null,
    price numeric(12,2) not null,
    bill_date integer not null,
    frequency text not null, -- 'monthly' | 'yearly'
    payment_method text not null,
    status text not null, -- 'active' | 'paused' | 'cancelled' | 'trial'
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.subscriptions enable row level security;

drop policy if exists "Acceso completo a suscripciones propias" on public.subscriptions;
create policy "Acceso completo a suscripciones propias"
    on public.subscriptions for all
    using (auth.uid()::text = user_id or user_id = 'local_user')
    with check (auth.uid()::text = user_id or user_id = 'local_user');


-- 7. TABLA: WARRANTIES (Garantías)
create table if not exists public.warranties (
    id bigint generated by default as identity primary key,
    user_id text not null,
    product_name text not null,
    brand text not null,
    model text,
    serial_number text,
    store text not null,
    purchase_date text not null,
    price numeric(12,2) not null,
    duration_months integer not null,
    expiry_date text not null,
    receipt_image text,
    support_contact text,
    notes text,
    status text not null, -- 'active' | 'expiring' | 'expired' | 'claim'
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.warranties enable row level security;

drop policy if exists "Acceso completo a garantías propias" on public.warranties;
create policy "Acceso completo a garantías propias"
    on public.warranties for all
    using (auth.uid()::text = user_id or user_id = 'local_user')
    with check (auth.uid()::text = user_id or user_id = 'local_user');


-- 8. TABLA: PACKAGES (Rastreo de envíos)
create table if not exists public.packages (
    id bigint generated by default as identity primary key,
    user_id text not null,
    carrier text not null,
    tracking_number text not null,
    description text not null,
    status text not null, -- 'transit' | 'delivered' | 'failed'
    estimated_delivery text,
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.packages enable row level security;

drop policy if exists "Acceso completo a paquetes propios" on public.packages;
create policy "Acceso completo a paquetes propios"
    on public.packages for all
    using (auth.uid()::text = user_id or user_id = 'local_user')
    with check (auth.uid()::text = user_id or user_id = 'local_user');


-- 9. TABLA: HOMES (Propiedades)
create table if not exists public.homes (
    id bigint generated by default as identity primary key,
    user_id text not null,
    name text not null,
    address text,
    type text not null, -- 'apartment' | 'house' | 'office' | 'other'
    rooms text[] default array[]::text[],
    services text[] default array[]::text[],
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.homes enable row level security;

drop policy if exists "Acceso completo a viviendas propias" on public.homes;
create policy "Acceso completo a viviendas propias"
    on public.homes for all
    using (auth.uid()::text = user_id or user_id = 'local_user')
    with check (auth.uid()::text = user_id or user_id = 'local_user');


-- 10. TABLA: HOME MAINTENANCE (Mantenimiento de Hogar)
create table if not exists public.home_maintenance (
    id bigint generated by default as identity primary key,
    home_id bigint references public.homes(id) on delete cascade not null,
    title text not null,
    date text not null,
    cost numeric(12,2) not null,
    contractor text,
    notes text
);

alter table public.home_maintenance enable row level security;

drop policy if exists "Acceso completo a mantenimientos de viviendas propias" on public.home_maintenance;
create policy "Acceso completo a mantenimientos de viviendas propias"
    on public.home_maintenance for all
    using (
        exists (
            select 1 from public.homes 
            where public.homes.id = home_id 
            and (public.homes.user_id = auth.uid()::text or public.homes.user_id = 'local_user')
        )
    );


-- 11. TABLA: TASKS (Tareas / Checklist)
create table if not exists public.tasks (
    id bigint generated by default as identity primary key,
    user_id text not null,
    title text not null,
    due_date text,
    due_time text,
    priority text not null, -- 'high' | 'medium' | 'low'
    category text default 'Personal',
    notes text,
    tags text[] default array[]::text[],
    is_completed boolean default false,
    parent_id bigint references public.tasks(id) on delete cascade,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.tasks enable row level security;

drop policy if exists "Acceso completo a tareas propias" on public.tasks;
create policy "Acceso completo a tareas propias"
    on public.tasks for all
    using (auth.uid()::text = user_id or user_id = 'local_user')
    with check (auth.uid()::text = user_id or user_id = 'local_user');


-- 12. TABLA: ACTIVITIES (Bitácora Auditoría)
create table if not exists public.activities (
    id bigint generated by default as identity primary key,
    user_id text not null,
    action text not null,
    module text not null,
    details text not null,
    date timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.activities enable row level security;

drop policy if exists "Acceso completo a actividades propias" on public.activities;
create policy "Acceso completo a actividades propias"
    on public.activities for all
    using (auth.uid()::text = user_id or user_id = 'local_user')
    with check (auth.uid()::text = user_id or user_id = 'local_user');


-- 13. TABLA: HEALTH_RECORDS (Expediente Médico & Salud)
create table if not exists public.health_records (
    id bigint generated by default as identity primary key,
    user_id text not null,
    record_type text not null,
    title text not null,
    doctor_name text,
    doctor_phone text,
    blood_type text,
    allergies text,
    medications text,
    dosage text,
    frequency_time text,
    date text,
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.health_records enable row level security;
drop policy if exists "Acceso a registros de salud" on public.health_records;
create policy "Acceso a registros de salud" on public.health_records for all using (auth.uid()::text = user_id or user_id = 'local_user');


-- 14. TABLA: PASSWORD_RECORDS (Bóveda de Contraseñas Cifradas)
create table if not exists public.password_records (
    id bigint generated by default as identity primary key,
    user_id text not null,
    title text not null,
    category text not null,
    account_username text,
    encrypted_secret text not null,
    secret_iv text,
    url text,
    notes text,
    is_favorite boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.password_records enable row level security;
drop policy if exists "Acceso a bóveda de contraseñas" on public.password_records;
create policy "Acceso a bóveda de contraseñas" on public.password_records for all using (auth.uid()::text = user_id or user_id = 'local_user');


-- 15. TABLA: FINANCIAL_GOALS (Patrimonio & Metas de Ahorro)
create table if not exists public.financial_goals (
    id bigint generated by default as identity primary key,
    user_id text not null,
    title text not null,
    category text not null,
    target_amount numeric not null,
    current_amount numeric default 0,
    target_date text,
    status text default 'active',
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.financial_goals enable row level security;
drop policy if exists "Acceso a metas financieras" on public.financial_goals;
create policy "Acceso a metas financieras" on public.financial_goals for all using (auth.uid()::text = user_id or user_id = 'local_user');


-- 16. TABLA: TRAVEL_RECORDS (Viajes e Itinerarios)
create table if not exists public.travel_records (
    id bigint generated by default as identity primary key,
    user_id text not null,
    destination text not null,
    country text,
    start_date text not null,
    end_date text,
    budget numeric,
    status text default 'planned',
    flights text,
    lodging text,
    packing_list jsonb default '[]'::jsonb,
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.travel_records enable row level security;
drop policy if exists "Acceso a viajes" on public.travel_records;
create policy "Acceso a viajes" on public.travel_records for all using (auth.uid()::text = user_id or user_id = 'local_user');


-- 17. TABLA: HABIT_RECORDS (Hábitos Diarios & Rachas)
create table if not exists public.habit_records (
    id bigint generated by default as identity primary key,
    user_id text not null,
    title text not null,
    category text,
    frequency_days integer default 7,
    completed_dates text[] default array[]::text[],
    streak integer default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.habit_records enable row level security;
drop policy if exists "Acceso a hábitos" on public.habit_records;
create policy "Acceso a hábitos" on public.habit_records for all using (auth.uid()::text = user_id or user_id = 'local_user');


-- 18. TABLA: QUICK_NOTE_RECORDS (Notas Adhesivas / Sticky Notes)
create table if not exists public.quick_note_records (
    id bigint generated by default as identity primary key,
    user_id text not null,
    title text,
    content text not null,
    color text default 'bg-amber-500/10 border-amber-500/30 text-amber-300',
    pinned boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.quick_note_records enable row level security;
drop policy if exists "Acceso a notas adhesivas" on public.quick_note_records;
create policy "Acceso a notas adhesivas" on public.quick_note_records for all using (auth.uid()::text = user_id or user_id = 'local_user');


-- 19. TABLA: JOURNAL_RECORDS (Diario Personal & Mood Tracker)
create table if not exists public.journal_records (
    id bigint generated by default as identity primary key,
    user_id text not null,
    date text not null,
    mood text not null,
    title text not null,
    content text not null,
    tags text[],
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.journal_records enable row level security;
drop policy if exists "Acceso a diario personal" on public.journal_records;
create policy "Acceso a diario personal" on public.journal_records for all using (auth.uid()::text = user_id or user_id = 'local_user');


-- 20. TABLA: PANTRY_ITEMS (Despensa & Lista de Compras)
create table if not exists public.pantry_items (
    id bigint generated by default as identity primary key,
    user_id text not null,
    name text not null,
    category text not null,
    quantity numeric default 1,
    unit text default 'piezas',
    expiry_date text,
    is_low boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.pantry_items enable row level security;
drop policy if exists "Acceso a despensa" on public.pantry_items;
create policy "Acceso a despensa" on public.pantry_items for all using (auth.uid()::text = user_id or user_id = 'local_user');


-- 21. TABLA: PET_RECORDS (Ficha de Mascotas & Carnet Veterinario)
create table if not exists public.pet_records (
    id bigint generated by default as identity primary key,
    user_id text not null,
    pet_name text not null,
    species text not null,
    breed text,
    birth_date text,
    weight numeric,
    medical_notes text,
    vaccinations jsonb default '[]'::jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.pet_records enable row level security;
drop policy if exists "Acceso a expediente de mascotas" on public.pet_records;
create policy "Acceso a expediente de mascotas" on public.pet_records for all using (auth.uid()::text = user_id or user_id = 'local_user');


-- 22. TABLA: USER_SETTINGS (Sincronización Rápida de Planes & Supabase Admin)
create table if not exists public.user_settings (
    id uuid default gen_random_uuid() primary key,
    user_id text unique not null,
    display_name text,
    password_hash text,
    plan text default 'free',
    billing_cycle text,
    active_modules jsonb,
    pin_enabled boolean default false,
    theme text default 'dark',
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Asegurar columna password_hash si la tabla ya existía anteriormente
alter table public.user_settings add column if not exists password_hash text;

alter table public.user_settings enable row level security;
drop policy if exists "Acceso completo a user_settings" on public.user_settings;
create policy "Acceso completo a user_settings" on public.user_settings for all using (true);


-- 23. TABLA: CALENDAR_EVENTS (Eventos Personalizados, Cumpleaños y Recordatorios)
create table if not exists public.calendar_events (
    id bigint generated by default as identity primary key,
    user_id text not null,
    title text not null,
    date text not null,
    time text,
    category text default 'birthday',
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.calendar_events enable row level security;
drop policy if exists "Acceso a eventos de calendario propios" on public.calendar_events;
create policy "Acceso a eventos de calendario propios" on public.calendar_events for all using (auth.uid()::text = user_id or user_id = 'local_user');



